### ISSUE TITLE
Optimize BE keyword search custom resolver by reducing number of database queries

### ISSUE THREAD

**Issue by jameshbarton** [openpracticelibrary/opl-content-api#54]
As Nova, I need to be able to retrieve results from keyword searches as quickly as possible, so that I may view relevant practices to my current need in a timely manner.

ACCEPTANCE CRITERIA
Given I am on the all practices page 
When I choose to search practices
Then Practices should be filtered based on the keyword(s) typed into the search box
And the backend query should complete with as few database queries as possible

NOTES

See comments on openpracticelibrary/opl-content-api#31 .  This operation currently requires three separate database operations.  At least two of these should be consolidated into a single query.

**Comment by omcneil** [comment]
Complete
