### ISSUE TITLE
Set up editor roles in opl-content-api

### ISSUE THREAD

**Issue by shaheinm** [openpracticelibrary/opl-content-api#59]
As an RBAC service, I need to provide an editor role, so that I can determine who is capable of publishing content.

**ACCEPTANCE CRITERIA**
**Given** A user with the Editor role
**When** I approve the publish of a practice
**Then** The practice is published
**And** A user without the Editor role cannot submit practices directly to the content-api.

**Comment by omcneil** [comment]
No longer needed
