### ISSUE TITLE
Server Side AMA (3)

### ISSUE THREAD

**Issue by shaheinm** [openpracticelibrary/opl-content-api#9]
As a system, I need to organize the AMA content so that I can provide the data in a sensible way.

**ACCEPTANCE CRITERIA**

**Given** A request for Practice Page content
**When** I respond to the request
**Then** All questions and associated answers (and associated comments on those answers) should be available for query.
**And** Email is created and sent for all submitted questions

**NOTES**
- This will require updates to the data model
  - First Name, Last Name, Email - all non-required fields
- [Front-end work associated](https://github.com/openpracticelibrary/opl-fe/issues/22)

**BLOCKERS**
None

**Comment by jameshbarton** [comment]
To map better to the designs, the model changes include adding a name and email, with the name having a default value of Anonymous User.
